version: '3.8'

services:
  java-service:
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
    networks:
      docker-local-network:
        ipv4_address: 192.168.100.80
    container_name: java-service

networks:
  docker-local-network:
    external: true
